### PR TITLE
Created EDA Reports

### PR DESCRIPTION
**Pull request by PythonCoderUnicorn**
Hi
I created HTML and pdf EDA reports for everyone's use.

### CODE REVIEW

**Review by rladiesPHL — CHANGES_REQUESTED** [review]
1) why is the data dictionary changed? if just formatting changes, please do not include that file in PR;
2)  the directory names "Reports" and "work" are unclear (e.g. are these final reports for ElderNet? what kind of work?); for EDA reports, please create a folder under /data, called "eda_reports", and save the files there; for "work", if this is work in progress for team3, you may want to make sure it's in the team3 directory, and keep it in the forked repo for now (so, exclude it from the PR), while you're actively working on it.

**Comment by PythonCoderUnicorn** [comment]
The data dictionary changed only due to knitting the file and viewing it in visual mode. Nothing else changed.

The Reports folder has EDA reports for each dataset in the data/ 
Screen Shot 2022-02-17 at 11 44 01 AM

each report has different statistics, some have basic stats and others have qq plot and boxplots, correlations and missing value counts.

Sorry about the work/  folder, I forgot I set that up, it just has the R code of how the EDA reports were generated and right now is Team agnostic to which team it is for, it is *just* EDA reports.

**Comment by rladiesPHL** [comment]
sounds good; we'd still like to keep the directory structure clean and easy to understand, so I can merge the PR if you can rename the Reports directory to "EDA Reports" (upper/lowercase doesn't matter) and move it under "/data" so people can find it as they are exploring the data. Since the file in "work" is directly related to these EDA reports, can you rename it to "EDA_report_generation" or something equally informative, and save it also under the same "EDA Reports" subdirectory (inside /data)? 

the PR should therefore just add 1 subdirectory with all the EDA report files and report generation script to /data, with no other additions to main folder structure

**Comment by PythonCoderUnicorn** [comment]
Okay I followed the comments and `EDA Reports/`  has `EDA_report_create/` which has the `dataExplore.R` file

**Pull request merged**
